#SMTP Configuration
#Tue Oct 28 02:52:37 WEST 2025
mail.from=talbimanal28@gmail.com
mail.smtp.host=smtp.gmail.com
mail.smtp.password=vnvk dkbi tucp cohp
mail.smtp.port=25
mail.smtp.user=talbimanal28@gmail.com
